config/routes.rb
Rails.application.routes.draw do
  resources :categories
  get 'subscribers/index'
  get 'orderitems/index'
  get 'orderitems/show'
  get 'orderitems/new'
  get 'orderitems/edit'
  
  resources :orders do
    resources:orderitems
  end
  
  devise_for :users do 
    resources :orders 
  end
  
  get '/checkout' => 'cart#createOrder'
  
  get 'cart/index'
  resources :items
  # get 'static_pages/home'
  # get 'static_pages/about'
  root to: 'static_pages#home'
  
  get '/about' => 'static_pages#about'
  get '/home' => 'static_pages#home'
  
  get '/login' => 'user#login'
  get '/logout' => 'user#logout'
  
  get '/cart/clear' => 'cart#clear'
  get '/cart', to: 'cart#index'
  get '/cart/:id', to: 'cart#add'
  get '/cart/remove/:id' => 'cart#remove'
  
  get '/cart/decrease/:id' => 'cart#decrease'
  get '/cart/increase/:id' => 'cart#increase'
  
  get 'category/:title', to: 'static_pages#category'
  
  post '/search' => 'items#search'
  
  
  resources :subscribers
  get '/subsribers', to: 'subscribers#index'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  def index
    @items = Item.all
  end

  # GET /items/1
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  def create
    @item = Item.new(item_params)

    if @item.save
      redirect_to @item, notice: 'Item was successfully created.'
    else
      render :new
    end
  end
  
  def search
    st = "%#{params[:q]}%"
    @items = Item.where("title like ?", st)
  end

  # PATCH/PUT /items/1
  def update
    if @item.update(item_params)
      redirect_to @item, notice: 'Item was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /items/1
  def destroy
    @item.destroy
    redirect_to items_url, notice: 'Item was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def item_params
      params.require(:item).permit(:title, :description, :price, :image_url, :category, :brand, :product_id, :dimensions, :composition)
    end
    
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<div class="mainCont">
<%= form_with(model: item, local: true) do |form| %>
<div class="field">
<%= form.label :title %>
<%= form.text_field :title, id: :item_titl, :type =>"text"%>
</div>
<div class="field">
<%= form.label :description %>
<%= form.text_field :description, id: :item_description, :type =>"text" %>
</div>
<div class="field">
<%= form.label :price %>
<%= form.text_field :price, id: :item_price, :type =>"text" %>
</div>
<div class="field">
<%= form.label :image_url %>
<%= form.text_field :image_url, id: :item_image_url %>
</div>
<div class="field">
<%= form.label :category %>
<%= form.text_field :category, id: :item_category, :type =>"text" %>
</div>
<div class="field">
<%= form.label :brand %>
<%= form.text_field :brand, id: :item_brand, :type =>"text" %>
</div>

<div class="field">
<%= form.label :product_id %>
<%= form.text_field :product_id, id: :item_product_id, :type =>"text" %>
</div>

<div class="field">
<%= form.label :dimensions %>
<%= form.text_field :dimensions, id: :item_dimensions, :type =>"text" %>
</div>

<div class="field">
<%= form.label :composition %>
<%= form.text_field :composition, id: :item_composition, :type =>"text" %>
</div>


<div class="actions">
<%= form.submit %>
</div>
<% end %>
</div>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path, :class => "button btn btn-info", :role => "button" %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<div class="itemsContainer">
  <div class="item-image">
        <% @items.each do |item| %>
          <div class="itemhols">
          <p class="item-heading"><%= item.title %></p>
          <%= link_to (image_tag item.image_url, :class => "item-image"), item %>
          
          <p>Price <%= number_to_currency(item.price, :unit => "€") %>
          <br>
          Category: <%= item.category %>
          <br>
          Brand: <%= item.brand %></p>
          
          <%= link_to 'More detail', item, :class => "button btn btn-info", :role => "button" %>
          
          <a href="/cart/<%= item.id %>" class="button btn btn-info">Add To Cart</a>
          
          <% if session[:login]==1%>
          <%= link_to 'Edit', edit_item_path(item), :class => "button btn btn-success", :role => "button" %>
          <%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' }, :class => "button btn btn-danger", :role => "button" %>
          <% end %>
          </p>
          </div>
          <% end %>
          <br>
    </div>
  </div>
   
    
    

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/search.html.erb
<h2>You Searched Our Product Catalog For <%= @search_term %></h2>
<% if @items.length == 0 %>
<br />
<h2>No products were found to match your search</h2>
<% end %>
<table class="catalog">
<% @items.each do |item| %>
<tr>
<td>
<div class="image">
<%= link_to (image_tag item.image_url, :style => "height:100px"), item %>
</div>
<div class="title">
<%= link_to item.title, item %>
</div>
<div class="description">
<%= item.description %>
</div>
<div class="price">
<%= number_to_currency(item.price, :unit => "€") %>
</div>
<div class="links">
<% if user_signed_in? %>
<%= link_to 'Edit', edit_item_path(item) %>
<%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %>
<%else%>
<a href="/cart/<%= item.id %>">Add to Cart</a>
<%end%>
</div>
</td>
</tr>
<% end %>
</table>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @item.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>Category:</strong>
  <%= @item.category %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @item.brand %>
</p>

<p>
  <strong>Product:</strong>
  <%= @item.product_id %>
</p>

<p>
  <strong>Dimensions:</strong>
  <%= @item.dimensions %>
</p>

<p>
  <strong>Composition:</strong>
  <%= @item.composition %>
</p>

<%= link_to 'Back', items_path, :class => "button btn btn-info", :role => "button" %>