config/routes.rb
Rails.application.routes.draw do
  resources :categories
  get 'subscribers/index'
  get 'orderitems/index'
  get 'orderitems/show'
  get 'orderitems/new'
  get 'orderitems/edit'
  
  resources :orders do
    resources:orderitems
  end
  
  devise_for :users do 
    resources :orders 
  end
  
  get '/checkout' => 'cart#createOrder'
  
  get 'cart/index'
  resources :items
  # get 'static_pages/home'
  # get 'static_pages/about'
  root to: 'static_pages#home'
  
  get '/about' => 'static_pages#about'
  get '/home' => 'static_pages#home'
  
  get '/login' => 'user#login'
  get '/logout' => 'user#logout'
  
  get '/cart/clear' => 'cart#clear'
  get '/cart', to: 'cart#index'
  get '/cart/:id', to: 'cart#add'
  get '/cart/remove/:id' => 'cart#remove'
  
  get '/cart/decrease/:id' => 'cart#decrease'
  get '/cart/increase/:id' => 'cart#increase'
  
  get 'category/:title', to: 'static_pages#category'
  
  post '/search' => 'items#search'
  
  
  resources :subscribers
  get '/subsribers', to: 'subscribers#index'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  
  def order_params
    
  params.require(:order).permit( :order_date, :user_id, :status)
  end
  
  has_many :orderitems

end

app/models/orderitem.rb
class Orderitem < ApplicationRecord
  belongs_to :order
end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
    validates :name,:email, :source, presence:true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  def user_params
  params.require(:user).permit(:email, :password, :password_confirmation, :remember_me)
  end
  
  has_many :orders       
         
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  before_action :authenticate_user!
  
  def add
        # get the id of the product
        id = params[:id]
        
        # if the cart exists use it, or if not make a new cart.
        
        if session[:cart] then
          cart = session[:cart]
        else
          session[:cart] = {}
          cart = session[:cart]
        end  
        
        # check if item is there and if so increment the quantity by 1
        # if the item is not there then set the quantity to be 1
        
        if cart[id] then
          cart[id] = cart[id] + 1
        else
          cart[id] = 1
        end 
    
    redirect_to :action => :index
  end
  
  def clear
    session[:cart] = nil
    redirect_to :action => :index
  end
    
  
  def remove
    id = params[:id]
    cart = session[:cart]
    cart.delete id
    redirect_to :action => :index
  end
  
  def decrease
    id = params[:id]
    cart = session[:cart]
    if cart[id]>=1
    cart[id] = cart[id] - 1
    end
    redirect_to :action => :index
  end
  
  
  def increase
    id = params[:id]
    cart = session[:cart]
    cart[id] = cart[id] + 1
    
    redirect_to :action => :index
  end
  
  
  def index
    # pass the cart to be displayed
    
    if session[:cart] then
      @cart = session[:cart]
    else
      @cart = {}
    end
    
  end
  
  
  
  
def createOrder
  
# @orderNo = Order.new(order_params) #find(params[:id])
  
  
 # Step 1: Get the current user
 @user = User.find(current_user.id)

 # Step 2: Create a new order and associate it with the current user
 @order = @user.orders.build(:order_date => DateTime.now, :status => 'Pending')
 @order.save

 # Step 3: For each item in the cart, create a new item on the order!!
 @cart = session[:cart] || {} # Get the content of the Cart
 @cart.each do | id, quantity |
   item = Item.find_by_id(id)
   @orderitem = @order.orderitems.build(:item_id => item.id, :title => item.title, :description => item.description, :quantity => quantity, :price=> item.price)
   @orderitem.save
 end
 
 @orders = Order.all
 @orderitems = Orderitem.where(order_id: Order.last)
 
 session[:cart] = nil # Hidden for development so I can refresh the page
 
end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  def index
    @items = Item.all
  end

  # GET /items/1
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  def create
    @item = Item.new(item_params)

    if @item.save
      redirect_to @item, notice: 'Item was successfully created.'
    else
      render :new
    end
  end
  
  def search
    st = "%#{params[:q]}%"
    @items = Item.where("title like ?", st)
  end

  # PATCH/PUT /items/1
  def update
    if @item.update(item_params)
      redirect_to @item, notice: 'Item was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /items/1
  def destroy
    @item.destroy
    redirect_to items_url, notice: 'Item was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def item_params
      params.require(:item).permit(:title, :description, :price, :image_url, :category, :brand, :product_id, :dimensions, :composition)
    end
    
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  def index
    @orders = Order.all
  end

  # GET /orders/1
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  def create
    @order = Order.new(order_params)

    if @order.save
      redirect_to @order, notice: 'Order was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /orders/1
  def update
    if @order.update(order_params)
      redirect_to @order, notice: 'Order was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /orders/1
  def destroy
    @order.destroy
    redirect_to orders_url, notice: 'Order was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def order_params
      params.require(:order).permit(:order_date, :user_id, :status)
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
    

 def login
 session[:login] = 1
 session[:cart] = nil
 flash[:notice] = "You are logged in!!"
 redirect_to :controller => :items
 end

 def logout
 session[:login] = nil
 session[:cart] = nil
 flash[:notice] = "You have been successfully logged out!!"
 redirect_to :controller => :items
 end


    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orderitems_helper.rb
module OrderitemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/_categories.html.erb
<% @categories.each do |category| %>
    
    <section>
    <div class="container-fluid ">
   
      <div class="col-xs-2">
 
        <p class="item-heading"><%= category.title %> </p>
        <p><%= category.description %></p>
        <i class="fa fa-shopping-bag fa-4x"></i>
        <p><a href="/category/<%= category.title %>" class="button"><%= category.title %></a></p>
      </div> 
      
      </div>

  </section>

    
    <% if @categories.length == 0 %>
        <br />
        <h2>There are currently no products in this category</h2>
    <% end %>
    
<% end %>

app/views/layouts/_footer.erb
  
  <footer class="bg-light text-center text-lg-start">
  <% if session[:login]==1%>
  <%= link_to 'New Item', new_item_path, :class =>"btn btn-success", :role=>"button" %>
   <%= link_to 'New Category', new_category_path, :class =>"btn btn-success", :role=>"button" %>
  <% end %>
    
  
      <div class="container-fluid">
      <div class="socials">
        <i class="social-icon fa fa-twitter"></i>
        <i class="social-icon fa fa-facebook-f"></i>
        <i class="social-icon fa fa-instagram"></i>
        <i class="social-icon fa fa-envelope"></i>
      </div>
      
      <%= link_to 'Newsletter sign-up', '/subscribers', :class =>"btn btn-success", :role=>"button" %>
      
            
            <form class="form-inline">
                <%=render 'layouts/search'%>
            </form>
          
      
        <!-- Copyright -->
        <div class="text-center p-3">
          © <%= Date.today.year %> Copyright:
          <i class="text-dark">christina caldwell </i>
        </div>
        
    </div>

</footer>

app/views/layouts/_header.erb
<header> 
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                    <button type="button" class="btn btn-light" data-toggle="modal" data-target="#loginModal"><i class="fa fa-user-o"></i>
                    </button>
                    <!-- Modal -->
                    <div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                      <div class="modal-dialog" role="document">
                        <div class="modal-content">
                          <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">My Account</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                              <span aria-hidden="true">&times;</span>
                            </button>
                          </div>
                          
                          <div class="modal-body">
                               <% if user_signed_in? %>
                                  <a href="#">Hi <%= current_user.email %></a>
                                  <%= link_to 'Edit Profile', edit_user_registration_path %>
                                  <%= link_to 'Sign out', destroy_user_session_path, :method => :delete %>
                                  <% else %>
                                  <%= link_to 'Sign in', new_user_session_path %>
                                  <%= link_to 'Register', new_user_registration_path %>
                                  <% end %>
                                  
                                  <%= link_to 'Newsletter sign-up', '/subscribers', :class =>"btn btn-success", :role=>"button" %>
                                  
                          </div> 
                          
                          <div id='admin-section' class="modal-body">     
                                <%= link_to "Admin Log In", login_path %>
                                <%= link_to "Admin Log Out", logout_path %>
                          </div>
                          
                          <div class="modal-footer">

                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                          </div>
                        </div>
                      </div>
                    </div> 

        </ul>
    </div>
    <div class="mx-auto order-0">
        <a class="navbar-brand mx-auto">Handbag Adore</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".dual-collapse2">
            <span class="navbar-toggler-icon"></span>
        </button>
    </div>
    <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
        <ul class="navbar-nav ml-auto">
            
            <li class="nav-item">
                
                <button type="button" class="btn btn-dark"><%= link_to '      Shopping Cart', "/cart", :class => "nav-link fa fa-shopping-bag" %></i>
                </button>
                
                
            </li>
        </ul>
    </div>
</nav>
  </header>
  
  

  

app/views/layouts/_navbar.erb
      <nav class="nav justify-content-center"> 
        <a class="nav-item"><%= link_to "Lookbook", "/" %></a>
        <a class="nav-item"><%= link_to "Shop", "/items"%></a>
        <a class="nav-item"><%= link_to "About", about_path %></a> 

        
      </nav>

app/views/layouts/_search.erb
<%= form_tag("/search", :method => "post") do %>
<%= label_tag(:q, "Search for:") %>
<%= text_field_tag(:q) %>
<%= submit_tag("Search") %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> Handbag Adore Store</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  
  </head>

<body> 
  
  <%= render 'layouts/header' %>
  
  <!--<p class="notice"><%= notice %></p>-->
  <!--<p class="alert"><%= alert %></p>-->
  <%= render 'layouts/navbar' %>
  
  <div class="container">
     <%= yield %>
  </div>
  
  <%= render 'layouts/footer' %>
  
</body>
</html>